---
title: "Title"
author: "Author Name"
date: "yyyy-mm-dd"
output: 
 html_document: 
  theme: journal
  number_sections: TRUE
  toc: TRUE
  toc_float: TRUE
  code_folding: show
---

```{r, include=FALSE}
# パッケージの呼び出し
library(knitr)
library(tableone)
library(labelled)
library(kableExtra)
library(rms)
library(survival)
library(survminer)

# チャンクオプションのデフォルト値指定
opts_chunk$set(echo = FALSE, 
               error = FALSE, 
               warning = FALSE,
               comment = NULL)
```

```{r, include=FALSE}
# データファイルの読みこみは表示する必要がないためinclude=FALSE
new <- read.csv(file = "new.csv")
```

# 背景表

研究対象者の手術時の背景情報を要約．

連続変数は平均値および標準偏差，離散変数は割合および対象者数で要約した．

```{r}
var_label(new) <- list(sex_lab = "Sex",
                       age = "Age on surgery",
                       ps_lab = "Performance Status",
                       depth_mm = "Depth [mm]")
tb <- CreateTableOne(vars = c("sex_lab", "age", "ps_lab", "depth_mm"),
                     strata = "treat_lab",
                     data = new,
                     test = FALSE,
                     smd = TRUE,
                     addOverall = FALSE)
tb1 <- print(x = tb, missing = TRUE, format = "pf", nonnormal = FALSE, smd = TRUE, varLabels = TRUE, pr = FALSE)

kable(x = tb1, format = "html", digits = 2) %>% 
  add_header_above(c("Patients' Baseline Characteristics" = 5)) %>% 
  kable_styling(full_width = FALSE)
```

# Kaplan-Meier曲線

治療有無で群別した各群に含まれる対象者の平均的な累積生存確率を，Kaplan-Meier法に基づいて推定した．

```{r}
fit <- survfit(formula = Surv(time = years_fu, event = event_y1) ~ treat_lab, data = new)

p_km <- ggsurvplot(fit = fit,  # survfit()関数で推定したオブジェクト
                data = new,      # データフレーム
                censor = TRUE,  # 対象者の打ち切りを示す+マークの表示有無
                conf.int = TRUE, # 95%信頼区間の表示有無
                # リスクテーブルの付記
                risk.table = TRUE,         # リスクテーブルの有無
                risk.table.col = "strata", # 群別した場合の色分け．"black"で黒に指定可．
                risk.table.height = 0.15,  # リスクテーブルの配置の高さ．
                tables.theme = theme_cleantable(), # リスクテーブルのテーマ
                # 見栄えの調整
                size = 1.5,                                   # ラインの太さ
                linetype = c("solid", "dashed"),              # ラインの種類
                xlab = "Follow-up time (Years)",                     # X軸ラベル
                ylab = "Cumulative Survival Probability",     # Y軸ラベル
                break.x.by = 1,    # X軸の目盛を"1"刻みで表示
                break.y.by = 0.1,  # Y軸の目盛を"0.1"刻みで表示
                legend.title = "",                  # 凡例タイトル
                legend.labs = c("Treated", "Untreated"))  # 凡例ラベル

# plot成分の調整
plt <- p_km$plot
p_km$plot <- plt + 
  theme(legend.title = element_blank(),
        legend.position = c(0.9, 0.9),
        legend.justification = c("right","top"),
        legend.key.width = unit(2, "cm"))
p_km
```

# 多変量Coxの比例ハザード回帰モデル

Coxの比例ハザード回帰モデルを用いて各因子が及ぼす影響を評価した．

```{r}
dd <- datadist(new)
options(datadist = "dd")

set.seed(1)
areg <- aregImpute(formula = ~ years_fu + event_y1 + treat_lab + depth_cm + age + ps_lab, data = new, n.impute = 5, pr = FALSE)
fmi <- fit.mult.impute(formula = Surv(time = years_fu, event = event_y1) ~ treat_lab + depth_cm + age + ps_lab, data = new, fitter = cph, xtrans = areg, pr = FALSE)
res <- summary(fmi)

tb <- res[c(1,3,5,7,9,11),c(4,6,7)]
tb <- as.data.frame(tb)
tb2 <- upData(object = tb,
              Effect = exp(Effect),
              `Lower 0.95` = exp(`Lower 0.95`),
              `Upper 0.95` = exp(`Upper 0.95`), print = FALSE)
rownames(x = tb2) <- c("Depth(cm)", "Age(y)", "Treated/Untreated", "PS (1/0)", "PS (2/0)", "PS (3/0)")
colnames(x = tb2) <- c("Hazard Ratio", "95% CI Lower", "95% CI Upper")

kable(x = tb2, format = "html", digits = 2) %>% 
  add_header_above(c(" " = 1, "Multivariable Cox proportional-hazard regression analysis" = 3)) %>% 
  add_footnote(label = c("Hazard Ratios per IQR were presented for continuous variables.",
                         "Missing values were imputed using a multiple impuatation approach.")) %>%
  kable_styling(full_width = FALSE)
```
